export type {
	ConfidenceDto as ConfidenceResult,
	DashboardStateDto as DashboardState,
	MarketBreakdownDto as MarketBreakdown,
	MarketSnapshotDto as MarketSnapshot,
	PaperStatsDto as PaperStats,
	PaperStatsResponseDto as PaperStatsResponse,
	PaperTradeEntryDto as PaperTradeEntry,
	RiskConfigDto as RiskConfig,
	StopLossStatusDto as StopLossStatus,
	TodayStatsDto as TodayStats,
	TradeRecordDto as TradeRecord,
} from "@orakel/shared/contracts";
